ALTER TABLE machines
ALTER COLUMN stream_state SET DEFAULT 'UNKNOWN';

ALTER TABLE machines
ALTER COLUMN signal_state SET DEFAULT 'UNKNOWN';

ALTER TABLE machines
ALTER COLUMN level_state SET DEFAULT 'UNKNOWN';

ALTER TABLE machines
ALTER COLUMN mute_state SET DEFAULT 'UNKNOWN';

ALTER TABLE machines
ALTER COLUMN routing_state SET DEFAULT 'UNKNOWN';